repos:
  # Black for Python code formatting
  - repo: https://github.com/psf/black
    rev: "@latest"  # Always use the latest version
    hooks:
      - id: black

  # Flake8 for linting Python code
  - repo: https://github.com/PyCQA/flake8
    rev: "@latest"  # Always use the latest version
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear  # Optional advanced linting plugin

  # isort for sorting imports
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: "@latest"  # Always use the latest version
    hooks:
      - id: isort

  # Yamllint for YAML syntax and style checking
  - repo: https://github.com/adrienverge/yamllint
    rev: "@latest"  # Always use the latest version
    hooks:
      - id: yamllint
        args: [--strict]

  # Pre-commit hooks for general file fixes
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "@latest"  # Always use the latest version
    hooks:
      - id: trailing-whitespace  # Removes trailing whitespace
      - id: end-of-file-fixer    # Ensures files end with a single newline
      - id: check-yaml           # Validates YAML syntax
      - id: check-json           # Validates JSON syntax
      - id: check-added-large-files  # Warns about committing large files
      - id: fix-encoding-pragma  # Adds encoding pragma to Python files

  # EditorConfig consistency check
  - repo: https://github.com/editorconfig-checker/editorconfig-checker
    rev: "@latest"  # Always use the latest version
    hooks:
      - id: editorconfig-checker

  # Shell scripts linting with ShellCheck
  - repo: https://github.com/koalaman/shellcheck
    rev: "@latest"  # Always use the latest version
    hooks:
      - id: shellcheck

  # Markdown linting
  - repo: https://github.com/markdownlint/markdownlint
    rev: "@latest"  # Always use the latest version
    hooks:
      - id: markdownlint

