[tool.poetry]
name = "half-stack-python"
version = "0.1.0"
description = ""
authors = ["CJ Steiner <clintonsteiner@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
