name: Lint RST Files
"on": [push, pull_request]

jobs:
  lint-rst:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          python-version: '3.13'
          enable-cache: true

      - name: Install linters
        run: |
          uv sync --only-group lint

      - name: Lint RST files
        run: uv run rstcheck **/*.rst

      - name: Lint YAML files
        run: |
          files="$(find . -name "*.yml" -o -name "*.yaml")"
          if [ -n "$files" ]; then
            uv run yamllint --config-data "{extends: default, rules: {document-start: {present: false}}}" $files
          else
            echo "no files to lint"
          fi

      - name: Lint Jupyter notebooks
        run: |
          for notebook in **/*.ipynb; do
            uv run jupyter nbconvert --to notebook --execute "$notebook"
          done
...
