name: Sphinx build

on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      publish:
        type: string
        default: 'false'

jobs:
  sphinx-build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    container:
      image: ghcr.io/${{ github.repository_owner }}/pandoc-ubuntu:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:

      - name: Build HTML
        run: make html

      - name: Upload artifacts
        if: ${{ inputs.publish == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          name: html-docs
          path: ./build/html/

      - name: Deploy
        if: ${{ (inputs.publish == 'true') && (github.ref == 'refs/heads/master') }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/html
