name: Sphinx build

on:  # yamllint disable-line rule:truthy
  workflow_run:
    workflows: ["Publish Ubuntu Pandoc Docker"]
    types: ["completed"]

jobs:
  sphinx-build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/pandoc-ubuntu:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:

      - name: Build HTML
        run: make html

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          github_token: ${{ secrets.github_token }}
          name: html-docs
          path: ./build/html/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.github_token }}
          publish_dir: ./build/html
